/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.jani.noppapeli;

import java.util.TimerTask;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Jani
 */
public class NoppaPeli extends javax.swing.JFrame {

    /**
     * Creates new form NoppaPeli
     */
    Noppa pelaajaNoppa1;
    Noppa pelaajaNoppa2;
    Noppa koneNoppa1;
    Noppa koneNoppa2;
    int koneSumma = 0;
    int pelaajaSumma = 0;
    public NoppaPeli() {
        initComponents();
        pelaajaNoppa1 = new Noppa();
        pelaajaNoppa2 = new Noppa();
        koneNoppa1 = new Noppa();
        koneNoppa2 = new Noppa();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtnHeita = new javax.swing.JButton();
        jlblNoppa1 = new javax.swing.JLabel();
        jlblNoppa2 = new javax.swing.JLabel();
        jlblPelaajaSumma = new javax.swing.JLabel();
        jlblKoneSumma = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbtnHeita.setText("Heitä");
        jbtnHeita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnHeitaActionPerformed(evt);
            }
        });

        jlblPelaajaSumma.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jlblPelaajaSumma.setText("Pelaaja Summa: ");

        jlblKoneSumma.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jlblKoneSumma.setText("Kone Summa: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(jbtnHeita)
                .addContainerGap(219, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlblNoppa1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlblNoppa2)
                        .addGap(63, 63, 63))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlblPelaajaSumma)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlblKoneSumma)
                        .addGap(88, 88, 88))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblPelaajaSumma)
                    .addComponent(jlblKoneSumma))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblNoppa1)
                    .addComponent(jlblNoppa2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 157, Short.MAX_VALUE)
                .addComponent(jbtnHeita)
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void jbtnHeitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnHeitaActionPerformed

        if (pelaajaSumma < 21) {
            pelaajaNoppa1.heita();
            pelaajaNoppa2.heita();

            jlblNoppa1.setIcon(pelaajaNoppa1.haeKuva());
            jlblNoppa2.setIcon(pelaajaNoppa2.haeKuva());

            pelaajaSumma += pelaajaNoppa1.haeLuku() + pelaajaNoppa2.haeLuku();
            jlblPelaajaSumma.setText(String.format("Pelaaja summa: %d", pelaajaSumma));
        }
        if (koneSumma < 21) {    
            koneNoppa1.heita();
            koneNoppa2.heita();
            koneSumma += koneNoppa1.haeLuku() + koneNoppa2.haeLuku();
            jlblKoneSumma.setText(String.format("Kone summa: %d", koneSumma));
        }
        if (pelaajaSumma > 21 && koneSumma > 21) {
            JOptionPane.showInternalMessageDialog(null, String.format("Kummatkin heitti yli 21, tasapeli.", koneSumma));
            pelaajaSumma = 0;
            koneSumma = 0;
            return;
        }
        
        if (pelaajaSumma > 21) {
            JOptionPane.showInternalMessageDialog(null, String.format("Heitit yli 21, kone voitti pisteillä %d", koneSumma));
            pelaajaSumma = 0;
            koneSumma = 0;
            return;
        }
        if (koneSumma > 21) {
            JOptionPane.showInternalMessageDialog(null, String.format("Kone heitti yli 21, voitit pisteillä %d", pelaajaSumma));
            pelaajaSumma = 0;
            koneSumma = 0;
            return;
        }
        
        /*TimerTask noppaHeitto = new TimerTask() {
            @Override
            public void run() {

            pelaajaNoppa1.heita();
            pelaajaNoppa2.heita();

            jlblNoppa1.setIcon(pelaajaNoppa1.haeKuva());
            jlblNoppa2.setIcon(pelaajaNoppa2.haeKuva());
            }
        };
        Timer noppaTimer = new Timer();
        */
        
        
    
        //jlblNoppa1.setText(String.format("Noppa 1 : %d", pelaajaNoppa1.haeLuku()));
        //jlblNoppa2.setText(String.format("Noppa 2 : %d", pelaajaNoppa2.haeLuku()));
    }//GEN-LAST:event_jbtnHeitaActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NoppaPeli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NoppaPeli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NoppaPeli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NoppaPeli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NoppaPeli().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtnHeita;
    private javax.swing.JLabel jlblKoneSumma;
    private javax.swing.JLabel jlblNoppa1;
    private javax.swing.JLabel jlblNoppa2;
    private javax.swing.JLabel jlblPelaajaSumma;
    // End of variables declaration//GEN-END:variables
}
