/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.jani.tilauslaskin;

import javax.swing.JOptionPane;

/**
 *
 * @author Jani
 */
public class Kayttoliittyma extends javax.swing.JFrame {

    /**
     * Creates new form Kayttoliittyma
     */
    public Kayttoliittyma() {
        initComponents();
        jrdVisa.setSelected(true);
        jrdVisa.setActionCommand("VISA");
        jrdTilisiirto.setActionCommand("TILISIIRTO");
        jrdKateinen.setActionCommand("KATEINEN");
        jlblSumma.setText("Tilauksen loppusumma (maksutapa: " + jtbngrpMaksutapa.getSelection().getActionCommand() + "): ");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtbngrpMaksutapa = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtxtMaara = new javax.swing.JTextField();
        jtxtHinta = new javax.swing.JTextField();
        jrdKateinen = new javax.swing.JRadioButton();
        jrdVisa = new javax.swing.JRadioButton();
        jrdTilisiirto = new javax.swing.JRadioButton();
        jbtnLaske = new javax.swing.JButton();
        jlblSumma = new javax.swing.JLabel();
        jtxtSumma = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tilauslaskin");

        jLabel1.setText("Määritä tuotteiden määrä, hinta ja maksutapa niin lasken loppusumman.");

        jLabel2.setText("Hinta/kpl:");

        jLabel3.setText("Määrä:");

        jtbngrpMaksutapa.add(jrdKateinen);
        jrdKateinen.setText("Käteinen +2% lisää hintaa");

        jtbngrpMaksutapa.add(jrdVisa);
        jrdVisa.setText("Visa -1% alennus");

        jtbngrpMaksutapa.add(jrdTilisiirto);
        jrdTilisiirto.setText("Tilisiirto kertamaksulla -2% alennus");

        jbtnLaske.setText("Laske");
        jbtnLaske.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLaskeActionPerformed(evt);
            }
        });

        jlblSumma.setText("Tilauksen loppusumma:");

        jtxtSumma.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(61, 61, 61)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtxtMaara, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                                    .addComponent(jtxtHinta)))
                            .addComponent(jbtnLaske)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlblSumma)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtxtSumma, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jrdTilisiirto)
                            .addComponent(jrdVisa, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrdKateinen, javax.swing.GroupLayout.Alignment.LEADING))))
                .addGap(73, 73, 73))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtxtMaara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxtHinta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jrdVisa)
                .addGap(18, 18, 18)
                .addComponent(jrdTilisiirto)
                .addGap(18, 18, 18)
                .addComponent(jrdKateinen)
                .addGap(30, 30, 30)
                .addComponent(jbtnLaske)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblSumma)
                    .addComponent(jtxtSumma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    double MAKSUTAPA_VISA = -1;
    double MAKSUTAPA_TILISIIRTO = -2;
    double MAKSUTAPA_KATEINEN = 2;
    private double haeValittuMaksutapaAlennus() {
        switch (jtbngrpMaksutapa.getSelection().getActionCommand()) {
            case "VISA":
                return MAKSUTAPA_VISA;
            case "TILISIIRTO":
                return MAKSUTAPA_TILISIIRTO;
            case "KATEINEN":
                return MAKSUTAPA_KATEINEN;
            default:
                throw new AssertionError();
        }
    }
    
    private void jbtnLaskeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLaskeActionPerformed
        int maara;
        double ahinta;
        double maksutapa;
        double summa;
        try {
            maara = Integer.valueOf(jtxtMaara.getText());
            ahinta = Double.valueOf(jtxtHinta.getText());
            maksutapa = haeValittuMaksutapaAlennus();
            
            if (maara <= 0 || ahinta <= 0) {
                 JOptionPane.showInternalMessageDialog(null, "Hinta tai määrä on väärin!\nVain positiivisia lukuja tekstikenttiin!", "Virhe", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if ( maara > 1000 || ahinta > 10000) {
                 JOptionPane.showInternalMessageDialog(null, "Hinta tai määrä on liian suuri!\nValitse hinta väliltä 1 - 10 000 ja määrä väliltä 1 - 1000!", "Virhe", JOptionPane.ERROR_MESSAGE);
                 return;
            }
        } catch (Exception e) {
            JOptionPane.showInternalMessageDialog(null, "Hinta tai määrä on väärin!\nSyötithän vain kokonaislukuja määrään ja kokonaislukuja/desimaaleja hintaan?", "Virhe", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        summa = ahinta*maara*(maksutapa+100.0)/100.0;
        jlblSumma.setText("Tilauksen loppusumma (maksutapa: " + jtbngrpMaksutapa.getSelection().getActionCommand() + "): ");
        jtxtSumma.setText(String.valueOf(summa));
    }//GEN-LAST:event_jbtnLaskeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kayttoliittyma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kayttoliittyma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kayttoliittyma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kayttoliittyma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kayttoliittyma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jbtnLaske;
    private javax.swing.JLabel jlblSumma;
    private javax.swing.JRadioButton jrdKateinen;
    private javax.swing.JRadioButton jrdTilisiirto;
    private javax.swing.JRadioButton jrdVisa;
    private javax.swing.ButtonGroup jtbngrpMaksutapa;
    private javax.swing.JTextField jtxtHinta;
    private javax.swing.JTextField jtxtMaara;
    private javax.swing.JTextField jtxtSumma;
    // End of variables declaration//GEN-END:variables
}
