/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.jani.forsilmukka;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Jani
 */
public class Kayttoliittyma extends javax.swing.JFrame {

    /**
     * Creates new form Kayttoliittyma
     */
    public Kayttoliittyma() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtxtNimi = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtxtIka = new javax.swing.JTextField();
        jbtnTervehdys = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JlstTervehdys = new javax.swing.JList<>();
        jtbnTervehdysTextarea = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtxtareaTervehdys = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Ole hyvä ja anna nimesi ja ikäsi vuosina.");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Nimi:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Ikä:");

        jbtnTervehdys.setText("Tervehdys");
        jbtnTervehdys.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTervehdysActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(JlstTervehdys);

        jtbnTervehdysTextarea.setText("Tervehdys");
        jtbnTervehdysTextarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbnTervehdysTextareaActionPerformed(evt);
            }
        });

        jtxtareaTervehdys.setColumns(20);
        jtxtareaTervehdys.setRows(5);
        jScrollPane2.setViewportView(jtxtareaTervehdys);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                        .addGap(39, 39, 39))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jbtnTervehdys, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtbnTervehdysTextarea, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(145, 145, 145))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtIka, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtNimi, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(jLabel1)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxtNimi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtxtIka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnTervehdys)
                    .addComponent(jtbnTervehdysTextarea))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /***
     * Tarkistaa tekstikenttien oikeellisuuden
     * @return Palauttaa true jos tekstikentät täytetty oikein, muussa tapauksessa false
     */
    private boolean tarkistaSyote() {
        int ika;
        try {
            ika = Integer.parseInt(jtxtIka.getText());
        } catch (Exception e) {
            JOptionPane.showInternalMessageDialog(null, "Ikä syötetty väärin!\nSyötithän vain numeroita?");
            return false;
        }
        if (jtxtNimi.getText().equals("")) {
            JOptionPane.showInternalMessageDialog(null, "Nimi tekstikenttä on tyhjä!");
            return false;
        }
        if (ika <= 0 || ika > 120) {
            JOptionPane.showInternalMessageDialog(null, "Mahdoton ikä syötetty!\n Syötä ikä väliltä 1-120");
            return false;
        }
        return true;
    }
    
    private void jbtnTervehdysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTervehdysActionPerformed
        if (!tarkistaSyote()) {
            return;
        }
        int ika;
        try {
            ika = Integer.parseInt(jtxtIka.getText());
        } catch (Exception e) {
            return;
        }
        
        DefaultListModel dlm = new DefaultListModel();
        
        for (int i = 0; i < ika; i++) {
            dlm.add(i, String.format("Hyvää syntymäpäivää:%s %d", jtxtNimi.getText(), i+1));
        }
        JlstTervehdys.setModel(dlm);
    }//GEN-LAST:event_jbtnTervehdysActionPerformed

    private void jtbnTervehdysTextareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbnTervehdysTextareaActionPerformed

        if (!tarkistaSyote()){
            return;
        }
        int ika;
        try {
            ika = Integer.parseInt(jtxtIka.getText());
        } catch (Exception e) {
            return;
        }
        String tervehdys = "";
        for (int i = 1; i <= ika; i++) {
            tervehdys +=  String.format("Hyvää syntymäpäivää:%s %d\n", jtxtNimi.getText(), i);
        }
        jtxtareaTervehdys.setText(tervehdys);
    }//GEN-LAST:event_jtbnTervehdysTextareaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kayttoliittyma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kayttoliittyma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kayttoliittyma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kayttoliittyma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kayttoliittyma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> JlstTervehdys;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbtnTervehdys;
    private javax.swing.JButton jtbnTervehdysTextarea;
    private javax.swing.JTextField jtxtIka;
    private javax.swing.JTextField jtxtNimi;
    private javax.swing.JTextArea jtxtareaTervehdys;
    // End of variables declaration//GEN-END:variables
}
