/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.jani.parturihinnoittelu;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Jani
 */
public class Kayttoliittyma extends javax.swing.JFrame {

    /**
     * Creates new form Kayttoliittyma
     */
    TilaustenHallinta tilaukset;
    public Kayttoliittyma() {
        initComponents();
        tilaukset = new TilaustenHallinta();
        jListValitutKasittelyt.setModel(new DefaultListModel());
        jListTilaukset.setModel(new DefaultListModel());
        jrbtnAikuinen.setActionCommand("Aikuinen");
        jrbtnLapsi.setActionCommand("Lapsi");
        jrbtnPitkat.setActionCommand("Pitkät");
        jrbtnKeskipitkat.setActionCommand("Keskipitkät");
        jrbtnLyhyet.setActionCommand("Lyhyet");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtngrpAsiakasika = new javax.swing.ButtonGroup();
        jbtngrpHiustenpituus = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jrbtnAikuinen = new javax.swing.JRadioButton();
        jrbtnLapsi = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jrbtnPitkat = new javax.swing.JRadioButton();
        jrbtnKeskipitkat = new javax.swing.JRadioButton();
        jrbtnLyhyet = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListKasittelyt = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListValitutKasittelyt = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        jbtnLisaakasittely = new javax.swing.JButton();
        jbtnPoistakasittely = new javax.swing.JButton();
        jchkInternetvaraus = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jtxtMaara = new javax.swing.JTextField();
        jbtnLisaatilaus = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListTilaukset = new javax.swing.JList<>();
        jbtnPoistatilaus = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jtxtHinta = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtxtTilauksetYhteensa = new javax.swing.JTextField();
        jbtnPoistaKaikkiTilaukset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hiustenkäsittely Hintalaskuri");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Asiakas");

        jbtngrpAsiakasika.add(jrbtnAikuinen);
        jrbtnAikuinen.setSelected(true);
        jrbtnAikuinen.setText("Aikuinen 25€");
        jrbtnAikuinen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbtnAikuinenActionPerformed(evt);
            }
        });

        jbtngrpAsiakasika.add(jrbtnLapsi);
        jrbtnLapsi.setText("Lapsi 15€");
        jrbtnLapsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbtnLapsiActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Hiusten pituus");

        jbtngrpHiustenpituus.add(jrbtnPitkat);
        jrbtnPitkat.setText("Pitkät 10€");
        jrbtnPitkat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbtnPitkatActionPerformed(evt);
            }
        });

        jbtngrpHiustenpituus.add(jrbtnKeskipitkat);
        jrbtnKeskipitkat.setText("Keskipitkät 5€");
        jrbtnKeskipitkat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbtnKeskipitkatActionPerformed(evt);
            }
        });

        jbtngrpHiustenpituus.add(jrbtnLyhyet);
        jrbtnLyhyet.setSelected(true);
        jrbtnLyhyet.setText("Lyhyet 0€");
        jrbtnLyhyet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbtnLyhyetActionPerformed(evt);
            }
        });

        jListKasittelyt.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Raidat,30€", "Koko pään värjäys,80€", "Juhlakampaus,50€", "Koekampaus,20€", "Pesu,10€", "Kiharrus,15€", "Permanentti,50€" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jListKasittelyt);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Saatavilla olevat käsittelyt");

        jScrollPane2.setViewportView(jListValitutKasittelyt);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Valitut käsittelyt");

        jbtnLisaakasittely.setText("LISÄÄ =>");
        jbtnLisaakasittely.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLisaakasittelyActionPerformed(evt);
            }
        });

        jbtnPoistakasittely.setText("<= POISTA");
        jbtnPoistakasittely.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPoistakasittelyActionPerformed(evt);
            }
        });

        jchkInternetvaraus.setText("Internet-varaus (5€ alennus jos kokonaissumma yli 25€)");
        jchkInternetvaraus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkInternetvarausActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Määrä");

        jtxtMaara.setText("1");

        jbtnLisaatilaus.setText("Lisää tilaus");
        jbtnLisaatilaus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLisaatilausActionPerformed(evt);
            }
        });

        jListTilaukset.setToolTipText("");
        jScrollPane3.setViewportView(jListTilaukset);

        jbtnPoistatilaus.setText("Poista tilaus");
        jbtnPoistatilaus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPoistatilausActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Hinta");

        jtxtHinta.setText("25.0");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Tilaukset yhteensä:");

        jbtnPoistaKaikkiTilaukset.setText("Poista kaikki tilaukset");
        jbtnPoistaKaikkiTilaukset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPoistaKaikkiTilauksetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrbtnLyhyet)
                            .addComponent(jrbtnKeskipitkat)
                            .addComponent(jrbtnPitkat)
                            .addComponent(jLabel2)
                            .addComponent(jrbtnLapsi)
                            .addComponent(jrbtnAikuinen)
                            .addComponent(jLabel1))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbtnLisaakasittely, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtnPoistakasittely))))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 3, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addGap(117, 117, 117))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jchkInternetvaraus)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtxtHinta, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                    .addComponent(jtxtMaara))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtTilauksetYhteensa)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnLisaatilaus)
                        .addGap(33, 33, 33)
                        .addComponent(jbtnPoistatilaus)
                        .addGap(72, 72, 72)
                        .addComponent(jbtnPoistaKaikkiTilaukset)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jrbtnAikuinen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jrbtnLapsi)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jrbtnPitkat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jrbtnKeskipitkat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jrbtnLyhyet)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(jbtnLisaakasittely)
                                .addGap(64, 64, 64)
                                .addComponent(jbtnPoistakasittely)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jchkInternetvaraus)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtxtMaara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jtxtHinta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnLisaatilaus)
                    .addComponent(jbtnPoistatilaus)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtxtTilauksetYhteensa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnPoistaKaikkiTilaukset))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnLisaakasittelyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLisaakasittelyActionPerformed
        if (jListKasittelyt.getSelectedIndex() == -1) {
            return;
        }
        
        DefaultListModel mdl = (DefaultListModel)jListValitutKasittelyt.getModel();
        for (int i = 0; i < mdl.getSize(); i++) {
            if (mdl.get(i).toString().equals(jListKasittelyt.getSelectedValue())) {
                return;
            }
        }
        mdl.addElement(jListKasittelyt.getSelectedValue());
        paivitaHintaTeksti();
    }//GEN-LAST:event_jbtnLisaakasittelyActionPerformed

    private void jbtnPoistakasittelyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPoistakasittelyActionPerformed

        if (jListValitutKasittelyt.getSelectedIndex() == -1) {
            return;
        }
        DefaultListModel mdl = (DefaultListModel)jListValitutKasittelyt.getModel();
        mdl.remove(jListValitutKasittelyt.getSelectedIndex());
        paivitaHintaTeksti();
    }//GEN-LAST:event_jbtnPoistakasittelyActionPerformed

    private void jrbtnAikuinenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbtnAikuinenActionPerformed
       paivitaHintaTeksti();
    }//GEN-LAST:event_jrbtnAikuinenActionPerformed

    private void jrbtnLapsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbtnLapsiActionPerformed
       paivitaHintaTeksti();
    }//GEN-LAST:event_jrbtnLapsiActionPerformed

    private void jrbtnPitkatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbtnPitkatActionPerformed
       paivitaHintaTeksti();
    }//GEN-LAST:event_jrbtnPitkatActionPerformed

    private void jrbtnKeskipitkatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbtnKeskipitkatActionPerformed
        paivitaHintaTeksti();
    }//GEN-LAST:event_jrbtnKeskipitkatActionPerformed

    private void jrbtnLyhyetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbtnLyhyetActionPerformed
        paivitaHintaTeksti();
    }//GEN-LAST:event_jrbtnLyhyetActionPerformed

    private void jchkInternetvarausActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkInternetvarausActionPerformed
        paivitaHintaTeksti();
    }//GEN-LAST:event_jchkInternetvarausActionPerformed

    private void jbtnPoistatilausActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPoistatilausActionPerformed
        int indeksi = jListTilaukset.getSelectedIndex();
        if (indeksi == -1) {
            return;
        }
        DefaultListModel mdl = (DefaultListModel)jListTilaukset.getModel();
        mdl.remove(indeksi);
        tilaukset.poistaTilaus(indeksi);
        paivitaTilaustenSummaTeksti();
    }//GEN-LAST:event_jbtnPoistatilausActionPerformed

    private String haeTilauksenNimi() {
        String nimi = jbtngrpAsiakasika.getSelection().getActionCommand();
        nimi += ", " + jbtngrpHiustenpituus.getSelection().getActionCommand();
        
        DefaultListModel mdl = (DefaultListModel)jListValitutKasittelyt.getModel();
        if (mdl.getSize() > 0) {
            nimi += " (";
        }
        for (int i = 0; i < mdl.getSize(); i++) {
            nimi += mdl.get(i).toString().split(",")[0];
            if (i != mdl.getSize()-1) {
                nimi += ", ";
            }
        }
        if (mdl.getSize() > 0) {
            nimi += ")";
        }
        return nimi;
    }
    private boolean tarkistaSyote() {
        try {
            int maara = Integer.valueOf(jtxtMaara.getText());
            if (maara <= 0 ) {
                JOptionPane.showInternalMessageDialog(null, "Määrä syötetty väärin!", "Virhe", JOptionPane.ERROR_MESSAGE);
                return false;
            }
            double hinta = Double.valueOf(jtxtHinta.getText());
            if (hinta <= 0) {
                JOptionPane.showInternalMessageDialog(null, "Hinta syötetty väärin!", "Virhe", JOptionPane.ERROR_MESSAGE);
                return false;
            }
        } catch (Exception e) {
            JOptionPane.showInternalMessageDialog(null, "Määrä tai hinta syötetty väärin!", "Virhe", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }
    
    private void paivitaTilaustenSummaTeksti() {
        DefaultListModel mdl = (DefaultListModel)jListTilaukset.getModel();
        double summa = 0;
        for (int i = 0; i < tilaukset.haeTilauslistaPituus(); i++) {
            summa += tilaukset.haeTilaus(i).haeHintaSumma();
        }
        jtxtTilauksetYhteensa.setText(String.format("%.2f €", summa));
    }
    
    private void jbtnLisaatilausActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLisaatilausActionPerformed
        
        if (!tarkistaSyote()) {
            return;
        }
        tilaukset.lisaaTilaus(haeTilauksenNimi(), laskeHinta(), Integer.valueOf(jtxtMaara.getText()));
        
        DefaultListModel mdl = (DefaultListModel)jListTilaukset.getModel();
        mdl.clear();
        for (int i = 0; i < tilaukset.haeTilauslistaPituus(); i++) {
            Tilaus tl = tilaukset.haeTilaus(i);
            mdl.addElement(String.format("%s | Määrä: %d | A'-Hinta: %.2f € | Summa: %.2f €", tl.haeNimi(), tl.haeMaara(), tl.haeHinta(), tl.haeHintaSumma()));
        }
        paivitaTilaustenSummaTeksti();
    }//GEN-LAST:event_jbtnLisaatilausActionPerformed

    private void jbtnPoistaKaikkiTilauksetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPoistaKaikkiTilauksetActionPerformed
        
        if (JOptionPane.showConfirmDialog(null, "Haluatko varmasti poistaa kaikki tilaukset?", "Varmistus", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION) {
            DefaultListModel mdl = (DefaultListModel)jListTilaukset.getModel();
            mdl.clear();
            tilaukset.poistaKaikkiTilaukset();
            paivitaTilaustenSummaTeksti();
        }
    }//GEN-LAST:event_jbtnPoistaKaikkiTilauksetActionPerformed

    private double laskeHinta() {
       if (!tarkistaSyote()) {
           return 0;
       }
        
       double hinta = 0;
       String asiakasIka = jbtngrpAsiakasika.getSelection().getActionCommand();
       String hiustenPituus = jbtngrpHiustenpituus.getSelection().getActionCommand();
        switch (asiakasIka) {
            case "Aikuinen":
                hinta += 25;
                break;
            case "Lapsi":
                hinta += 15;
                break;
            default:
                throw new AssertionError();
        }
        switch (hiustenPituus) {
            case "Pitkät":
                hinta += 10;
                break;
            case "Keskipitkät":
                hinta += 5;
                break;
            case "Lyhyet":
                break;
            default:
                throw new AssertionError();
        }
        
        DefaultListModel mdl = (DefaultListModel)jListValitutKasittelyt.getModel();
        for (int i = 0; i < mdl.getSize(); i++) {
            String kasittely = mdl.get(i).toString().replace("€", "").split(",")[1];
            int kasittelyHinta = Integer.valueOf(kasittely);
            hinta += kasittelyHinta;
        }
        int maara = 1;
        try {
            maara = Integer.valueOf(jtxtMaara.getText());
        } catch (Exception e) {
        }
        
        if (hinta*maara >= 25) {
            if (jchkInternetvaraus.isSelected()) {
                hinta -= 5;
            }
        }
       return hinta;
    }
    
    private void paivitaHintaTeksti() {
        jtxtHinta.setText(String.valueOf(laskeHinta()));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kayttoliittyma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kayttoliittyma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kayttoliittyma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kayttoliittyma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kayttoliittyma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList<String> jListKasittelyt;
    private javax.swing.JList<String> jListTilaukset;
    private javax.swing.JList<String> jListValitutKasittelyt;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton jbtnLisaakasittely;
    private javax.swing.JButton jbtnLisaatilaus;
    private javax.swing.JButton jbtnPoistaKaikkiTilaukset;
    private javax.swing.JButton jbtnPoistakasittely;
    private javax.swing.JButton jbtnPoistatilaus;
    private javax.swing.ButtonGroup jbtngrpAsiakasika;
    private javax.swing.ButtonGroup jbtngrpHiustenpituus;
    private javax.swing.JCheckBox jchkInternetvaraus;
    private javax.swing.JRadioButton jrbtnAikuinen;
    private javax.swing.JRadioButton jrbtnKeskipitkat;
    private javax.swing.JRadioButton jrbtnLapsi;
    private javax.swing.JRadioButton jrbtnLyhyet;
    private javax.swing.JRadioButton jrbtnPitkat;
    private javax.swing.JTextField jtxtHinta;
    private javax.swing.JTextField jtxtMaara;
    private javax.swing.JTextField jtxtTilauksetYhteensa;
    // End of variables declaration//GEN-END:variables
}
