/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.suorakaidepintaala;

import javax.swing.JOptionPane;

/**
 *
 * @author Jani
 */
public class Suorakaide extends javax.swing.JFrame {

    /**
     * Creates new form Suorakaide
     */
    public Suorakaide() {
        initComponents();
        jLabelKorkeusVirhe.setVisible(false);
        jLabelLeveysVirhe.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldLeveys = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldKorkeus = new javax.swing.JTextField();
        jButtonLaske = new javax.swing.JButton();
        jTextFieldPintaAla = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabelLeveysVirhe = new javax.swing.JLabel();
        jLabelKorkeusVirhe = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Anna Suorakaiteen leveys ja korkeus, lasken pinta-alan.");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Leveys (m)");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Korkeus (m)");

        jButtonLaske.setText("Laske");
        jButtonLaske.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLaskeActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Pinta-Ala (m2)");

        jLabelLeveysVirhe.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelLeveysVirhe.setForeground(new java.awt.Color(255, 51, 51));
        jLabelLeveysVirhe.setText("Virhe leveydessä.");

        jLabelKorkeusVirhe.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelKorkeusVirhe.setForeground(new java.awt.Color(255, 51, 51));
        jLabelKorkeusVirhe.setText("Virhe korkeudessa.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jButtonLaske)
                                    .addComponent(jTextFieldLeveys, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                                    .addComponent(jTextFieldKorkeus)
                                    .addComponent(jTextFieldPintaAla))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelLeveysVirhe)
                                    .addComponent(jLabelKorkeusVirhe)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldLeveys, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelLeveysVirhe))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldKorkeus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelKorkeusVirhe))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonLaske)
                .addGap(7, 7, 7)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldPintaAla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLaskeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLaskeActionPerformed
        double korkeus = 0;
        double leveys = 0;
        try {
            korkeus = Double.parseDouble(jTextFieldKorkeus.getText());
            jLabelKorkeusVirhe.setVisible(false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane,"Vain numeroita korkeus kentässä.", "Virhe", JOptionPane.ERROR_MESSAGE);
            jLabelKorkeusVirhe.setVisible(true);
        }
        try {
            leveys = Double.parseDouble(jTextFieldLeveys.getText());
            jLabelLeveysVirhe.setVisible(false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane,"Vain numeroita leveys kentässä.", "Virhe", JOptionPane.ERROR_MESSAGE);
            jLabelLeveysVirhe.setVisible(true);
            return;
        }
        if(korkeus <= 0 || leveys <= 0) {
            JOptionPane.showMessageDialog(rootPane,"Luvut oltava suurempi kuin 0.", "Virhe", JOptionPane.ERROR_MESSAGE);
            return;
        }
        double pintaAla = korkeus * leveys * 100;
        pintaAla = Math.round(pintaAla);
        pintaAla = pintaAla/100;
        jTextFieldPintaAla.setText(String.valueOf(pintaAla));
    }//GEN-LAST:event_jButtonLaskeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Suorakaide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Suorakaide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Suorakaide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Suorakaide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Suorakaide().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLaske;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelKorkeusVirhe;
    private javax.swing.JLabel jLabelLeveysVirhe;
    private javax.swing.JTextField jTextFieldKorkeus;
    private javax.swing.JTextField jTextFieldLeveys;
    private javax.swing.JTextField jTextFieldPintaAla;
    // End of variables declaration//GEN-END:variables
}
