/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.jani.asiakasrekisteri;

import java.sql.*;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;

/**
 *
 * @author Jani
 */
public class Kirjautuminen extends javax.swing.JFrame {

    /**
     * Creates new form Kayttoliittyma
     */
    public Kirjautuminen() {
        initComponents();
    }
    
    public Connection luoYhteys() {
        Connection cn = null;
        try {
            String kayttaja = "kehittaja";
            cn = DriverManager.getConnection("jdbc:mariadb://" + "localhost" + ":3306/ASIAKASTILAUSJARJESTELMA" + "?socketTimeout=2000", kayttaja, "SalaSana123!");
            return cn;
        }
        catch(SQLException ex) {
            System.out.println("Yhteyden luominen epäonnistui!:\n" + ex.getMessage());
            ex.printStackTrace();
            return null;
        }
    }

    private void sulje() {
        WindowEvent winClosingEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTervetuloa = new javax.swing.JLabel();
        jLabelTunnus = new javax.swing.JLabel();
        jLabelSalasana = new javax.swing.JLabel();
        jtxtTunnus = new javax.swing.JTextField();
        jchkNaytaSalasana = new javax.swing.JCheckBox();
        jbtnKirjaudu = new javax.swing.JButton();
        jtxtSalasana = new javax.swing.JPasswordField();
        jbtnYhteysTesti = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelTervetuloa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelTervetuloa.setText("Tervetuloa asiakastilaus-järjestelmään.");

        jLabelTunnus.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelTunnus.setText("Tunnus:");

        jLabelSalasana.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelSalasana.setText("Salasana:");

        jchkNaytaSalasana.setText("Näytä salasana");
        jchkNaytaSalasana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkNaytaSalasanaActionPerformed(evt);
            }
        });

        jbtnKirjaudu.setText("Kirjaudu");
        jbtnKirjaudu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnKirjauduActionPerformed(evt);
            }
        });

        jbtnYhteysTesti.setText("Yhteystesti");
        jbtnYhteysTesti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnYhteysTestiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jLabelTervetuloa))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelTunnus)
                                .addGap(18, 18, 18)
                                .addComponent(jtxtTunnus, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelSalasana)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtxtSalasana, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jchkNaytaSalasana)))))
                .addGap(35, 35, 35))
            .addGroup(layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(jbtnKirjaudu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnYhteysTesti)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabelTervetuloa)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTunnus)
                    .addComponent(jtxtTunnus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSalasana)
                    .addComponent(jchkNaytaSalasana)
                    .addComponent(jtxtSalasana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jbtnKirjaudu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jbtnYhteysTesti)
                .addContainerGap())
        );

        jLabelTervetuloa.getAccessibleContext().setAccessibleName("jLabelTervetuloa");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jchkNaytaSalasanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkNaytaSalasanaActionPerformed
        if (jchkNaytaSalasana.isSelected()) {
            jtxtSalasana.setEchoChar((char)0);
        }
        else {
            jtxtSalasana.setEchoChar('*');
        }
    }//GEN-LAST:event_jchkNaytaSalasanaActionPerformed

    private void jbtnKirjauduActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnKirjauduActionPerformed
        // TODO: käsittele annetuilla tunnuksilla
        String tunnus = "HeikkiHuoltohenkilO";//jtxtTunnus.getText();
        String tietokantaSalasana = "";
        char[] tietokantaSalasanaTaulukko = null;
        // Salasana käsitellään char taulukkona jotta voimme hävittää sen muistista heti käytön jälkeen.
        // String muuttujana GC päättää milloin se poistetaan ohjelman muistista.
        char[] annettuSalasana = "KiSsa123#!".toCharArray();//jtxtSalasana.getPassword();
        
        Connection cn = luoYhteys();
        
        // Tätä ei kuuluisi tehdä käyttäjän puolella, nyt lataamme kenen tahansa salasanan muistiin.
        String sqlKysely = "SELECT TUNNUS, DES_DECRYPT(kayttaja.SALASANA, 'salainenavain') AS SALASANA FROM KAYTTAJA WHERE TUNNUS = ?";
        try {
            PreparedStatement stm = cn.prepareStatement(sqlKysely);
            //stm.setString(1, annettuSalasana.toString());
            stm.setString(1, tunnus);
            ResultSet tulos = stm.executeQuery();

            // Jos tulos.next, tunnus on oikein.
            if(tulos.next()) {
                tietokantaSalasana = tulos.getString("SALASANA").trim();
                tietokantaSalasanaTaulukko = tietokantaSalasana.toCharArray();
                if(Arrays.equals(tietokantaSalasanaTaulukko, annettuSalasana)) {
                    PaaKayttoliittyma GUI = new PaaKayttoliittyma(tunnus);
                    GUI.setVisible(true);
                    System.out.println("Käynnistetään pääkäyttöliittymä.");
                    sulje();
                }
            }       
            else {
                JOptionPane.showMessageDialog(this, "Tunnus tai salasana on väärin. Yritä uudelleen.");
            }
        }
        catch(SQLException ex) {
            Logger.getLogger(Kirjautuminen.class.getName()).log(Level.SEVERE, null, ex);
        }
        // Poista salasanat muistista
        Arrays.fill(tietokantaSalasanaTaulukko, '0');
        Arrays.fill(annettuSalasana, '0');
        tietokantaSalasana = "";


    }//GEN-LAST:event_jbtnKirjauduActionPerformed

    private void jbtnYhteysTestiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnYhteysTestiActionPerformed
        try {
            Class.forName("org.mariadb.jdbc.Driver");
        } catch (ClassNotFoundException e) {
            System.out.println("Missä on MariaDB JDBC ajuri? Oletko ladannut mariadb connectorin osoitteesta:" +
"https://mariadb.com/downloads/#connectors ja lisännyt sen Netbeansissä Asiakasrekisteri-Libraries-Add" +
"JAR/Folder kohdassa?");
            e.printStackTrace();
            return;
        }
        System.out.println("Mariadb JDBC Driver rekisteröity!");
        Connection cn = null;
        try {
            String kayttaja = "kehittaja";
            cn = DriverManager.getConnection("jdbc:mariadb://" + "localhost" + ":3306/ASIAKASTILAUSJARJESTELMA" + "?socketTimeout=2000", kayttaja, "SalaSana123!");
        }
        catch(SQLException ex) {
            System.out.println("Yhteyden luominen epäonnistui!:\n" + ex.getMessage());
            ex.printStackTrace();
            return;
        }
        if (cn != null) {
            System.out.println("Tietokantayhteys toimii.");
        }
        else {
            System.out.println("Tietokantayhteyttä ei muodostettu.");
        }
    }//GEN-LAST:event_jbtnYhteysTestiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kirjautuminen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kirjautuminen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kirjautuminen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kirjautuminen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kirjautuminen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelSalasana;
    private javax.swing.JLabel jLabelTervetuloa;
    private javax.swing.JLabel jLabelTunnus;
    private javax.swing.JButton jbtnKirjaudu;
    private javax.swing.JButton jbtnYhteysTesti;
    private javax.swing.JCheckBox jchkNaytaSalasana;
    private javax.swing.JPasswordField jtxtSalasana;
    private javax.swing.JTextField jtxtTunnus;
    // End of variables declaration//GEN-END:variables
}
