/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.jani.pizzalaskuri;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Jani
 */
public class Kayttoliittyma extends javax.swing.JFrame {

    /**
     * Creates new form Kayttoliittyma
     */
    TilaustenHallinta tilaukset;
    public Kayttoliittyma() {
        initComponents();
        jrdNormaali.setActionCommand("NormaaliKoko");
        jrdPerhe.setActionCommand("PerheKoko");
        tilaukset = new TilaustenHallinta();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtngrpKoko = new javax.swing.ButtonGroup();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jrdNormaali = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jrdPerhe = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jchkKinkku = new javax.swing.JCheckBox();
        jchkAnanas = new javax.swing.JCheckBox();
        jchkMeetwursti = new javax.swing.JCheckBox();
        jchkKana = new javax.swing.JCheckBox();
        jchkHerkkusieni = new javax.swing.JCheckBox();
        jchkAurajuusto = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jtxtHinta = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtxtMaara = new javax.swing.JTextField();
        jbtnTilaa = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtKuitti = new javax.swing.JTextArea();
        jtbnMuokkaa = new javax.swing.JButton();
        jbtnTyhjenna = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Pizzalaskuri");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Valitse koko, kappalemäärä ja hinta niin lasken pizzalle hinnan.");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Koko:");

        jbtngrpKoko.add(jrdNormaali);
        jrdNormaali.setSelected(true);
        jrdNormaali.setText("Normaali 5€");
        jrdNormaali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrdNormaaliActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Normaali ja perhepizzahintaan kuuluu pohja, tomaattikastike ja juusto.");

        jbtngrpKoko.add(jrdPerhe);
        jrdPerhe.setText("Perhe 9€");
        jrdPerhe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrdPerheActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Täytteet:");

        jchkKinkku.setText("Kinkku + 0,75 €");
        jchkKinkku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkKinkkuActionPerformed(evt);
            }
        });

        jchkAnanas.setText("Ananas + 0,50 €");
        jchkAnanas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkAnanasActionPerformed(evt);
            }
        });

        jchkMeetwursti.setText("Meetwursti + 0,50 €");
        jchkMeetwursti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkMeetwurstiActionPerformed(evt);
            }
        });

        jchkKana.setText("Kana + 0,80 €");
        jchkKana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkKanaActionPerformed(evt);
            }
        });

        jchkHerkkusieni.setText("Herkkusieni + 0,50 €");
        jchkHerkkusieni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkHerkkusieniActionPerformed(evt);
            }
        });

        jchkAurajuusto.setText("Aurajuusto + 0,50 €");
        jchkAurajuusto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkAurajuustoActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Hinta");

        jtxtHinta.setText("5");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Määrä");

        jtxtMaara.setText("1");
        jtxtMaara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtMaaraActionPerformed(evt);
            }
        });

        jbtnTilaa.setText("Tilaa");
        jbtnTilaa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTilaaActionPerformed(evt);
            }
        });

        jtxtKuitti.setColumns(20);
        jtxtKuitti.setRows(5);
        jScrollPane1.setViewportView(jtxtKuitti);

        jtbnMuokkaa.setText("Muokkaa Tilauksia");
        jtbnMuokkaa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbnMuokkaaActionPerformed(evt);
            }
        });

        jbtnTyhjenna.setText("Tyhjennä");
        jbtnTyhjenna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTyhjennaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jrdNormaali)
                                    .addComponent(jrdPerhe)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jchkKinkku)
                                    .addComponent(jchkAnanas)
                                    .addComponent(jchkMeetwursti)
                                    .addComponent(jchkKana)
                                    .addComponent(jchkHerkkusieni)
                                    .addComponent(jchkAurajuusto)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtxtHinta)
                                    .addComponent(jtxtMaara)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jbtnTilaa)
                                        .addGap(18, 18, 18)
                                        .addComponent(jtbnMuokkaa)
                                        .addGap(32, 32, 32)
                                        .addComponent(jbtnTyhjenna, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(0, 79, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jrdNormaali))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrdPerhe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jchkKinkku)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jchkAnanas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jchkMeetwursti)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jchkKana)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jchkHerkkusieni)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jchkAurajuusto)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtxtHinta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jtxtMaara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnTilaa)
                    .addComponent(jtbnMuokkaa)
                    .addComponent(jbtnTyhjenna))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean tarkistaSyotteet() {
        try {
            Integer.valueOf(jtxtMaara.getText());
            Double.valueOf(jtxtHinta.getText());
        } catch (Exception e) {
            //e.printStackTrace();
            JOptionPane.showInternalMessageDialog(null, "Määrä tai hinta syötetty väärin!", "Virhe", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }
    
    private double laskeHinta() {
        double hinta = 0;
        if (jbtngrpKoko.getSelection().getActionCommand().equals("NormaaliKoko")) {
            hinta += 5;
        }
        else if (jbtngrpKoko.getSelection().getActionCommand().equals("PerheKoko")){
            hinta += 9;
        }
        if (jchkKinkku.isSelected()) {
            hinta += 0.75;
        }
        if (jchkAnanas.isSelected()) {
            hinta += 0.5;
        }
        if (jchkMeetwursti.isSelected()) {
            hinta += 0.5;
        }
        if (jchkKana.isSelected()) {
            hinta += 0.8;
        }
        if (jchkHerkkusieni.isSelected()) {
            hinta += 0.5;
        }
        if (jchkAurajuusto.isSelected()) {
            hinta += 0.5;
        }
        try {
            int maara = Integer.valueOf(jtxtMaara.getText());
            hinta *= maara;
        } catch (Exception e) {
        }
        
        return hinta;
    }
    
    private void paivitaHintaTeksti() {
        jtxtHinta.setText(String.valueOf(laskeHinta()));
    }
    private void paivitaKuitti() {
        int tilausMaara = tilaukset.haeTilauslistaPituus();
        int tilausLoppusumma = 0;
        jtxtKuitti.setText("");
        jtxtKuitti.append("Tilaus | Määrä | A Hinta | Summa\n");
        for (int i = 0; i < tilausMaara; i++) {
            Tilaus tl = tilaukset.haeTilaus(i);
            tilausLoppusumma += tl.haeHintaYhteensa();
            String tilausTeksti = String.format("%s | %s | %s € | %s €\n", tl.haeNimi(), String.valueOf(tl.haeMaara()), String.valueOf(tl.haeHinta()), String.valueOf(tl.haeHintaYhteensa()));
            jtxtKuitti.append(tilausTeksti);
        }
        jtxtKuitti.append("----------\n");
        jtxtKuitti.append("YHTEENSÄ: " + String.valueOf(tilausLoppusumma) + " €");
    }
    private int haeMaara() {
        try {
            return Integer.valueOf(jtxtMaara.getText());
        } catch (Exception e) {
            JOptionPane.showInternalMessageDialog(null, "Määrä syötetty väärin!", "Virhe", JOptionPane.ERROR_MESSAGE);
            return 0;
        }
    }
    
    private String haeTaytteet() {
        String taytteet = "(";
        
        if (jchkKinkku.isSelected()) {
            taytteet += "kinkku,";
        }
        if (jchkAnanas.isSelected()) {
            taytteet += "ananas,";
        }
        if (jchkMeetwursti.isSelected()) {
            taytteet += "meetwursti,";
        }
        if (jchkKana.isSelected()) {
            taytteet += "kana,";
        }
        if (jchkHerkkusieni.isSelected()) {
            taytteet += "herkkusieni,";
        }
        if (jchkAurajuusto.isSelected()) {
            taytteet += "aurajuusto,";
        }
        
        taytteet += ")";
        if (taytteet.equals("()")) {
            taytteet = "";
        }
        return taytteet;
    }
    
    private void jbtnTilaaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTilaaActionPerformed
        if (!tarkistaSyotteet()) {
            return;
        }
        paivitaHintaTeksti();
        String tilausNimi = "";
        if (jbtngrpKoko.getSelection().getActionCommand().equals("NormaaliKoko")) {
            tilausNimi += "Normaali ";
        }
        else {
            tilausNimi += "Perhe ";
        }
        tilausNimi += haeTaytteet();
        tilaukset.lisaaTilaus(tilausNimi, laskeHinta(), haeMaara());
        paivitaKuitti();
    }//GEN-LAST:event_jbtnTilaaActionPerformed

    
    private void jrdNormaaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrdNormaaliActionPerformed
       paivitaHintaTeksti();
    }//GEN-LAST:event_jrdNormaaliActionPerformed

    private void jrdPerheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrdPerheActionPerformed
        paivitaHintaTeksti();
    }//GEN-LAST:event_jrdPerheActionPerformed

    private void jchkKinkkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkKinkkuActionPerformed
        paivitaHintaTeksti();
    }//GEN-LAST:event_jchkKinkkuActionPerformed

    private void jchkAnanasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkAnanasActionPerformed
        paivitaHintaTeksti();
    }//GEN-LAST:event_jchkAnanasActionPerformed

    private void jchkMeetwurstiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkMeetwurstiActionPerformed
        paivitaHintaTeksti();
    }//GEN-LAST:event_jchkMeetwurstiActionPerformed

    private void jchkKanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkKanaActionPerformed
        paivitaHintaTeksti();
    }//GEN-LAST:event_jchkKanaActionPerformed

    private void jchkHerkkusieniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkHerkkusieniActionPerformed
        paivitaHintaTeksti();
    }//GEN-LAST:event_jchkHerkkusieniActionPerformed

    private void jchkAurajuustoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkAurajuustoActionPerformed
        paivitaHintaTeksti();
    }//GEN-LAST:event_jchkAurajuustoActionPerformed

    private void jtxtMaaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtMaaraActionPerformed
        paivitaHintaTeksti();
    }//GEN-LAST:event_jtxtMaaraActionPerformed

    private void jbtnTyhjennaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTyhjennaActionPerformed
       tilaukset.poistaKaikkiTilaukset();
       paivitaKuitti();
    }//GEN-LAST:event_jbtnTyhjennaActionPerformed

    private void naytaIkkuna() {
        this.setEnabled(true);
    }
    
    private void jtbnMuokkaaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbnMuokkaaActionPerformed
       TilauksetKayttoliittyma thUI = new TilauksetKayttoliittyma(tilaukset);
       thUI.setVisible(true);
       this.setEnabled(false);
       thUI.addWindowListener(new WindowAdapter() {
       public void windowClosing(WindowEvent e) {
           paivitaKuitti();
           naytaIkkuna();
       }});
    }//GEN-LAST:event_jtbnMuokkaaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kayttoliittyma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kayttoliittyma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kayttoliittyma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kayttoliittyma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kayttoliittyma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnTilaa;
    private javax.swing.JButton jbtnTyhjenna;
    private javax.swing.ButtonGroup jbtngrpKoko;
    private javax.swing.JCheckBox jchkAnanas;
    private javax.swing.JCheckBox jchkAurajuusto;
    private javax.swing.JCheckBox jchkHerkkusieni;
    private javax.swing.JCheckBox jchkKana;
    private javax.swing.JCheckBox jchkKinkku;
    private javax.swing.JCheckBox jchkMeetwursti;
    private javax.swing.JRadioButton jrdNormaali;
    private javax.swing.JRadioButton jrdPerhe;
    private javax.swing.JButton jtbnMuokkaa;
    private javax.swing.JTextField jtxtHinta;
    private javax.swing.JTextArea jtxtKuitti;
    private javax.swing.JTextField jtxtMaara;
    // End of variables declaration//GEN-END:variables
}
